Added description of the project
michaelnotjackson/youtube_playlist pull request #1
Opened 2024-10-17 19:45 UTC by michaelnotjackson

2024-10-18 05:47 UTC, dKosarevsky commented on README.md
> +## Description
укажи ФИО, номер группы и тему

2024-10-18 05:49 UTC, dKosarevsky requested changes
- опиши архитектуру приложения
- укажи библиотеки, планируемые для использования
- укажи версии python, которые будет поддерживать приложение

2024-10-18 16:00 UTC, dKosarevsky commented on README.md
> +
укажи тему проекта

2024-10-18 16:01 UTC, dKosarevsky commented on README.md
> +
опиши архитектуру

2024-10-18 16:01 UTC, dKosarevsky commented on README.md
> +
добавь больше полезного функционала, пока слабовато для проекта

2024-10-18 16:03 UTC, dKosarevsky requested changes
пока выглядит очень просто, нужно больше полезной нагрузки, не получится закрыть весь проект внешними либами, fastapi и pydantic супер, но нужно больше собственной логики в проекте

2024-10-18 16:03 UTC, michaelnotjackson commented on README.md
> +
Разве то, что в Description - это не тема проекта?

2024-10-18 16:04 UTC, michaelnotjackson commented on README.md
> +
Не совсем понимаю, что может подразумеваться под архитектурой кроме задействованных классов и эндпоинтов?

2024-10-18 16:10 UTC, michaelnotjackson commented
> пока выглядит очень просто, нужно больше полезной нагрузки, не получится закрыть весь проект внешними либами, fastapi и pydantic супер, но нужно больше собственной логики в проекте

Разве по функционалу это сильно отличается от личного трекера задач из гугл дока с идеями для проектов? К тому же, кажется, здесь добавляется немного сложности из-за того, что необходимо либо встроить плеер ютуба, либо искать исходники видео и как-то стримить их через свой/сторонний веб плеер

2024-10-18 22:23 UTC, dKosarevsky commented
> > пока выглядит очень просто, нужно больше полезной нагрузки, не получится закрыть весь проект внешними либами, fastapi и pydantic супер, но нужно больше собственной логики в проекте
> 
> Разве по функционалу это сильно отличается от личного трекера задач из гугл дока с идеями для проектов? К тому же, кажется, здесь добавляется немного сложности из-за того, что необходимо либо встроить плеер ютуба, либо искать исходники видео и как-то стримить их через свой/сторонний веб плеер

Опиши это в ридми

2024-10-18 22:24 UTC, dKosarevsky commented on README.md
> +
в Description очевидно - Description, нужно указать тему

2024-10-18 22:38 UTC, dKosarevsky commented on README.md
> +
Архитектура — это не просто список классов и эндпоинтов. Твоя задача — описать как эти классы работают между собой, какие данные двигаются, и почему это всё вообще имеет смысл в твоём приложении. Должен быть чёткий план системы: как данные переходят между слоями, где у тебя точки расширения и что ты предусмотрел для масштабирования, ошибок и т.д.

Ты кидаешь список методов, но это только верхушка айсберга. 

- Где описание потоков данных?
- Как взаимодействуют компоненты?
- Что будет, если пользователь внесёт изменение в очередь или уберёт видео?
- Какие у тебя ограничения по очереди — бесконечная она или нет?
- Какие ошибки может возвращать твоё API и как их будешь обрабатывать?

Всё это нужно показать, чтобы архитектура реально имела смысл.

Поэтому давай так: распиши как данные двигаются через всю систему. Опиши модули, слои, взаимодействия, возможные фейлы и сценарии восстановления. И главное, не тупо перечисли, а покажи логику, почему ты это так сделал. Твой код должен не только работать, но и объяснять, как и почему он работает, даже если его читают люди, которые видят его впервые.

А пока это выглядит как «вот, у меня есть машина, она ездит». Ну окей, но как она ездит? Какая у неё коробка передач, сколько цилиндров в двигателе, и как ты её будешь чинить, если всё сломается?

Теперь стало понятнее, что подразумевается под архитектурой?

2024-10-24 18:49 UTC, dKosarevsky approved these changes
Приступай к разработке

2024-10-24 18:49 UTC, merged