Development
michaelnotjackson/youtube_playlist pull request #2
Opened 2024-11-07 01:31 UTC by michaelnotjackson

2024-11-18 00:05 UTC, dKosarevsky commented on models.py
> +async def video_from_url(video_url: str, client_session: ClientSession | None = None):
- rtype hint

2024-11-18 00:06 UTC, dKosarevsky commented on app.py
> +def get_video_by_id(video_id: str):
- rtype hint

2024-11-18 00:07 UTC, dKosarevsky commented on app.py
> +def force_play(video_id: int):
- rtype hint

2024-11-18 00:07 UTC, dKosarevsky commented on app.py
> +async def index():
- rtype hint

2024-11-18 00:07 UTC, dKosarevsky commented on app.py
> +def delete(video_id: str):
- rtype hint

2024-11-18 00:07 UTC, dKosarevsky commented on app.py
> +def reload_data():
- rtype hint

2024-11-18 00:08 UTC, dKosarevsky requested changes
необходимо:

- поправить код по комментам к ревью
- добавить инструкцию по запуску приложения
- написать тесты
- добавить test coverage
- запуск тестов в GA
- отображать плашку coverage в ридми

2024-11-18 08:03 UTC, michaelnotjackson commented on models.py
> +async def video_from_url(video_url: str, client_session: ClientSession | None = None):
Что это значит?

2024-11-23 18:16 UTC, dKosarevsky commented
any updates?

2024-11-23 18:31 UTC, michaelnotjackson commented
![image](https://github.com/user-attachments/assets/8ce2b321-f5f4-470b-8f4c-d95f425347dd)
?

2024-11-23 20:42 UTC, dKosarevsky commented on models.py
> +async def video_from_url(video_url: str, client_session: ClientSession | None = None):
https://docs.python.org/3/library/typing.html

2024-11-23 20:42 UTC, dKosarevsky commented
> ![image](https://private-user-images.githubusercontent.com/46103889/389218999-8ce2b321-f5f4-470b-8f4c-d95f425347dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzOTQ3NjMsIm5iZiI6MTczMjM5NDQ2MywicGF0aCI6Ii80NjEwMzg4OS8zODkyMTg5OTktOGNlMmIzMjEtZjVmNC00NzBiLThmNGMtZDk1ZjQyNTM0N2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDIwNDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMzdkZGU5MDU0MThhYzJmNjlhMTAyYjY1M2Q2MzYyNWM2ZGQyYzAzNjZlOGExOWRkMjQ1MmYyOWY1NTQ0MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hNCOhCWHxy4dN1VSD1axkvqKrPVwqu3f_4VWV_CW2A) ?

увидел, ответил

2024-11-23 21:27 UTC, dKosarevsky commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
для методов лучше константы завести, DRY и вот это всё

2024-11-23 21:52 UTC, michaelnotjackson commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
В смысле заменить ['GET', 'POST'] на константу GET_POST и т.д.?

2024-11-23 21:52 UTC, michaelnotjackson commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
Если так, то это только читаемость уменьшит

2024-11-25 18:41 UTC, dKosarevsky commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
например так:

```py
from pydantic import BaseModel, Field
from typing import Literal


class HttpMethods(BaseModel):
    GET: Literal["GET"] = Field(default="GET")
    POST: Literal["POST"] = Field(default="POST")
```

2024-11-25 18:56 UTC, michaelnotjackson commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
Так это же не делает лучше для DRY, разве нет? По итогу нам опять надо будет писать одно и то же, так ещё и, кажется, противоречит KISS, так-как увеличилось число кода, который, по факту, не несёт в себе смысловой нагрузки

2024-12-01 22:05 UTC, dKosarevsky commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
KISS и DRY работают вместе: Да, появляется немного больше кода, но это не случай “мусора ради мусора”. Код становится менее хрупким и проще в поддержке. DRY здесь реализуется через минимизацию дублирования, а KISS достигается через понятные именованные константы.

2024-12-01 22:40 UTC, michaelnotjackson commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
Ок, сделаю. Но я до сих пор не понимаю почему этот код уменьшает повторения и как он "сохраняет это простым"

2024-12-02 10:05 UTC, michaelnotjackson commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
Это не работает. Чтобы так делать нужно, либо при использовании писать HttpMethods.\_\_fields\_\_["GET"].default, либо не использовать pydantic, что нивелирует смысл данной правки, если я правлиьно понимаю

2024-12-07 15:41 UTC, dKosarevsky commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
<img width="252" alt="image" src="https://github.com/user-attachments/assets/88ba51ed-1da3-4692-b208-170ccb06a162">

2024-12-07 15:42 UTC, dKosarevsky commented on src/app.py
> +@app.route('/', methods=['GET', 'POST'])
> Но я до сих пор не понимаю

Постарайся

2024-12-08 11:09 UTC, dKosarevsky approved these changes

2024-12-08 11:09 UTC, merged